-- =====================================================================
--  SISTEMA DE ASIGNACIÓN DE LABORATORIOS — UPDS
--  Script 36: DATOS REALES — FACULTADES, DOCENTES Y MATERIAS (2026)
--  Sacados del Excel "ASIGNACIONES DE LABORATORIOS - ENERO 2026.xlsx"
--  (enero a octubre 2026), con nombres corregidos y sin duplicados.
--  Todo lo de Medicina usa la materia "Medicina (laboratorio)".
--  Ya aplicado en producción el 2026-10-10. Correr solo sobre una base
--  vacía de estos catálogos (si ya existen, falla y no guarda nada).
-- =====================================================================

begin;

insert into public.carreras (nombre, sigla, color) values
  ('Ingeniería de Sistemas', 'SIS', '#2563eb'),
  ('Ingeniería en Redes y Telecomunicaciones', 'RED', '#0891b2'),
  ('Ingeniería Industrial', 'IND', '#ea580c'),
  ('Ingeniería Comercial', 'COM', '#16a34a'),
  ('Medicina', 'MED', '#dc2626'),
  ('Administración de Empresas', 'ADM', '#7c3aed'),
  ('Contaduría Pública', 'CON', '#0d9488'),
  ('Marketing y Publicidad', 'MKT', '#db2777'),
  ('Ciencias de la Comunicación Social', 'CCS', '#ca8a04'),
  ('Psicología', 'PSI', '#9333ea'),
  ('Derecho', 'DER', '#475569');

insert into public.docentes (nombres, apellidos) values
  ('Diego', 'Aramayo'),
  ('Emily', 'Arteaga'),
  ('Wilber', 'Baspineiro'),
  ('Javier', 'Bonifaz'),
  ('Wilmer', 'Campos'),
  ('José', 'Castro'),
  ('Ysnaider', 'Castro'),
  ('Abel', 'Catari'),
  ('Roger', 'Choque'),
  ('María', 'Colque'),
  ('Wilson', 'Cruz'),
  ('Sergio', 'Cruz Sequeiros'),
  ('José', 'Cuéllar'),
  ('Pedro Luis', 'Díaz'),
  ('Alex', 'Escobar'),
  ('Antonio', 'García'),
  ('Ruth', 'Gascher'),
  ('Teresa', 'Gutiérrez'),
  ('Hugo', 'Guzmán'),
  ('Andrés', 'Heredia'),
  ('Lili', 'Jiménez'),
  ('Teresa', 'Justiniano'),
  ('Andrés', 'Lobatón'),
  ('Jared', 'López'),
  ('Javier', 'López'),
  ('Miguel', 'Macías'),
  ('Lucero', 'Mamani'),
  ('Paul', 'Melgar'),
  ('Wilder', 'Mendoza'),
  ('Betty', 'Meneses'),
  ('Mariel', 'Morales'),
  ('Yolanda', 'Morón'),
  ('Pablo', 'Moscoso'),
  ('Álvaro', 'Moscoso'),
  ('Javier', 'Orosco'),
  ('Luis', 'Orozco'),
  ('Iván', 'Paz'),
  ('Carla', 'Peña'),
  ('Gustavo', 'Pérez'),
  ('Jenny', 'Quiroga'),
  ('Jimmy', 'Requena'),
  ('Edmundo', 'Rivas'),
  ('Naín', 'Rivas'),
  ('César', 'Rodríguez'),
  ('Hernán', 'Rodríguez'),
  ('Daniel', 'Román'),
  ('Mario', 'Saavedra'),
  ('Gineth', 'Salo'),
  ('Mauren', 'Salvatierra'),
  ('Héctor', 'Serrano'),
  ('David', 'Serrudo'),
  ('Elizabeth', 'Severiche'),
  ('Ernesto', 'Soto'),
  ('Gustavo', 'Tantani'),
  ('Daniela', 'Terán'),
  ('Freddy', 'Tinajeros'),
  ('Cristian', 'Torrez'),
  ('Jesús', 'Torrez'),
  ('David', 'Valverde'),
  ('Beatriz', 'Vargas'),
  ('Esther', 'Veizaga'),
  ('Lili', 'Veizaga'),
  ('Marco Antonio', 'Vidal'),
  ('Jeanine', 'Yépez'),
  ('Jaime', 'Zambrana'),
  ('Gabriela', 'Zimeri');

insert into public.docente_carreras (docente_id, carrera_id)
select dc.id, ca.id from (values
  ('Diego', 'Aramayo', 'RED'),
  ('Emily', 'Arteaga', 'MED'),
  ('Wilber', 'Baspineiro', 'COM'),
  ('Javier', 'Bonifaz', 'RED'),
  ('Wilmer', 'Campos', 'MED'),
  ('José', 'Castro', 'SIS'),
  ('José', 'Castro', 'RED'),
  ('María', 'Colque', 'SIS'),
  ('María', 'Colque', 'RED'),
  ('Wilson', 'Cruz', 'SIS'),
  ('Wilson', 'Cruz', 'RED'),
  ('Sergio', 'Cruz Sequeiros', 'DER'),
  ('José', 'Cuéllar', 'COM'),
  ('Alex', 'Escobar', 'SIS'),
  ('Alex', 'Escobar', 'RED'),
  ('Antonio', 'García', 'SIS'),
  ('Antonio', 'García', 'RED'),
  ('Ruth', 'Gascher', 'SIS'),
  ('Ruth', 'Gascher', 'RED'),
  ('Hugo', 'Guzmán', 'SIS'),
  ('Hugo', 'Guzmán', 'RED'),
  ('Hugo', 'Guzmán', 'MED'),
  ('Lili', 'Jiménez', 'SIS'),
  ('Lili', 'Jiménez', 'RED'),
  ('Andrés', 'Lobatón', 'RED'),
  ('Jared', 'López', 'SIS'),
  ('Jared', 'López', 'RED'),
  ('Javier', 'López', 'SIS'),
  ('Javier', 'López', 'RED'),
  ('Miguel', 'Macías', 'SIS'),
  ('Miguel', 'Macías', 'RED'),
  ('Paul', 'Melgar', 'SIS'),
  ('Paul', 'Melgar', 'RED'),
  ('Wilder', 'Mendoza', 'COM'),
  ('Betty', 'Meneses', 'SIS'),
  ('Betty', 'Meneses', 'RED'),
  ('Yolanda', 'Morón', 'SIS'),
  ('Yolanda', 'Morón', 'RED'),
  ('Pablo', 'Moscoso', 'SIS'),
  ('Álvaro', 'Moscoso', 'SIS'),
  ('Luis', 'Orozco', 'SIS'),
  ('Luis', 'Orozco', 'RED'),
  ('Iván', 'Paz', 'RED'),
  ('Gustavo', 'Pérez', 'SIS'),
  ('Gustavo', 'Pérez', 'RED'),
  ('Jenny', 'Quiroga', 'DER'),
  ('Jimmy', 'Requena', 'SIS'),
  ('Jimmy', 'Requena', 'RED'),
  ('Edmundo', 'Rivas', 'SIS'),
  ('Edmundo', 'Rivas', 'RED'),
  ('Naín', 'Rivas', 'SIS'),
  ('Naín', 'Rivas', 'RED'),
  ('Hernán', 'Rodríguez', 'SIS'),
  ('Hernán', 'Rodríguez', 'RED'),
  ('Daniel', 'Román', 'SIS'),
  ('Daniel', 'Román', 'RED'),
  ('Gineth', 'Salo', 'MED'),
  ('Mauren', 'Salvatierra', 'MED'),
  ('David', 'Serrudo', 'SIS'),
  ('David', 'Serrudo', 'RED'),
  ('Elizabeth', 'Severiche', 'SIS'),
  ('Elizabeth', 'Severiche', 'RED'),
  ('Ernesto', 'Soto', 'SIS'),
  ('Ernesto', 'Soto', 'RED'),
  ('Gustavo', 'Tantani', 'SIS'),
  ('Gustavo', 'Tantani', 'RED'),
  ('Daniela', 'Terán', 'MKT'),
  ('Freddy', 'Tinajeros', 'MED'),
  ('Cristian', 'Torrez', 'SIS'),
  ('Cristian', 'Torrez', 'RED'),
  ('Beatriz', 'Vargas', 'SIS'),
  ('Beatriz', 'Vargas', 'RED'),
  ('Esther', 'Veizaga', 'SIS'),
  ('Esther', 'Veizaga', 'RED'),
  ('Lili', 'Veizaga', 'SIS'),
  ('Lili', 'Veizaga', 'RED'),
  ('Marco Antonio', 'Vidal', 'SIS'),
  ('Marco Antonio', 'Vidal', 'RED'),
  ('Jaime', 'Zambrana', 'SIS'),
  ('Jaime', 'Zambrana', 'RED'),
  ('Gabriela', 'Zimeri', 'MKT')
) v(nombres, apellidos, sigla)
join public.docentes dc on dc.nombres = v.nombres and dc.apellidos = v.apellidos
join public.carreras ca on ca.sigla = v.sigla;

insert into public.materias (nombre) values
  ('Administración de Base de Datos I'),
  ('Antenas y Propagación'),
  ('Análisis de Sistemas y Señales'),
  ('Aplicaciones Móviles'),
  ('Auditoría de Sistemas'),
  ('Base de Datos I'),
  ('Base de Datos II'),
  ('Campos Electromagnéticos'),
  ('Circuitos Eléctricos II'),
  ('Comunicaciones Digitales I'),
  ('Cálculo I'),
  ('Deontología'),
  ('Derecho Administrativo y Regulatorio'),
  ('Derecho de Hidrocarburos'),
  ('Desarrollo de Sistemas I'),
  ('Desarrollo de Sistemas II'),
  ('Dibujo Computarizado'),
  ('Diseño Gráfico'),
  ('Diseño Web I'),
  ('Diseño Web II'),
  ('Electrónica II'),
  ('Estadística Descriptiva'),
  ('Estadística Inferencial'),
  ('Estructura de Datos'),
  ('Estructuras Discretas'),
  ('Fundamentos de Sistemas de Comunicación'),
  ('Hardware, Software y Redes'),
  ('Herramientas Digitales'),
  ('Informática Educativa'),
  ('Ingeniería de Software I'),
  ('Ingeniería de Software II'),
  ('Inglés Técnico I'),
  ('Inglés Técnico II'),
  ('Instalación y Certificación de Redes'),
  ('Inteligencia Artificial'),
  ('Inteligencia de Negocios'),
  ('Investigación Operativa I'),
  ('Investigación de Mercado I'),
  ('Medicina (laboratorio)'),
  ('Medios de Transmisión'),
  ('Modalidad de Grado - Examen de Grado Redes'),
  ('Modalidad de Grado - Examen de Grado Sistemas'),
  ('Modalidad de Grado - Proyectos'),
  ('Planificación de Marketing'),
  ('Programación Básica'),
  ('Programación I'),
  ('Programación II'),
  ('Programación III'),
  ('Programación IV'),
  ('Programación Numérica'),
  ('Programación Web I'),
  ('Programación Web II'),
  ('Programación de Aplicaciones'),
  ('Redes I'),
  ('Redes II'),
  ('Redes III'),
  ('Redes IV'),
  ('Redes Inalámbricas y Móviles'),
  ('Robótica'),
  ('Seguridad Informática'),
  ('Seguridad en Redes'),
  ('Sistemas Digitales I'),
  ('Sistemas Digitales II'),
  ('Sistemas Multimedia'),
  ('Sistemas Operativos I'),
  ('Sistemas Operativos II'),
  ('Sistemas de Comunicación Óptica'),
  ('Sistemas de Información I'),
  ('Sistemas de Información II'),
  ('Sistemas de Información III'),
  ('Sistemas de Radiocomunicación I'),
  ('Sistemas de Radiocomunicación II'),
  ('Taller de Redes'),
  ('Taller de Sistemas Operativos I'),
  ('Taller de Sistemas Operativos II'),
  ('Tecnología Web I'),
  ('Tecnología Web II'),
  ('Tecnología de Base de Datos I'),
  ('Tecnologías Inalámbricas'),
  ('Trading');

insert into public.docente_materias (docente_id, materia_id)
select dc.id, m.id from (values
  ('Abel', 'Catari', 'Cálculo I'),
  ('Alex', 'Escobar', 'Administración de Base de Datos I'),
  ('Alex', 'Escobar', 'Estructuras Discretas'),
  ('Alex', 'Escobar', 'Hardware, Software y Redes'),
  ('Alex', 'Escobar', 'Programación Básica'),
  ('Alex', 'Escobar', 'Programación II'),
  ('Alex', 'Escobar', 'Sistemas Digitales I'),
  ('Alex', 'Escobar', 'Sistemas Digitales II'),
  ('Alex', 'Escobar', 'Sistemas Operativos I'),
  ('Alex', 'Escobar', 'Taller de Sistemas Operativos I'),
  ('Andrés', 'Lobatón', 'Antenas y Propagación'),
  ('Andrés', 'Lobatón', 'Redes Inalámbricas y Móviles'),
  ('Andrés', 'Lobatón', 'Sistemas de Radiocomunicación II'),
  ('Antonio', 'García', 'Dibujo Computarizado'),
  ('Beatriz', 'Vargas', 'Programación II'),
  ('Beatriz', 'Vargas', 'Sistemas de Información III'),
  ('Betty', 'Meneses', 'Informática Educativa'),
  ('Betty', 'Meneses', 'Modalidad de Grado - Proyectos'),
  ('Cristian', 'Torrez', 'Campos Electromagnéticos'),
  ('Cristian', 'Torrez', 'Dibujo Computarizado'),
  ('Daniel', 'Román', 'Administración de Base de Datos I'),
  ('Daniel', 'Román', 'Aplicaciones Móviles'),
  ('Daniel', 'Román', 'Diseño Web II'),
  ('Daniel', 'Román', 'Programación Web I'),
  ('Daniel', 'Román', 'Sistemas de Información III'),
  ('Daniela', 'Terán', 'Planificación de Marketing'),
  ('David', 'Serrudo', 'Administración de Base de Datos I'),
  ('David', 'Serrudo', 'Desarrollo de Sistemas I'),
  ('David', 'Serrudo', 'Diseño Web I'),
  ('David', 'Serrudo', 'Inteligencia de Negocios'),
  ('David', 'Serrudo', 'Sistemas de Información I'),
  ('David', 'Valverde', 'Diseño Gráfico'),
  ('Diego', 'Aramayo', 'Análisis de Sistemas y Señales'),
  ('Diego', 'Aramayo', 'Estructuras Discretas'),
  ('Diego', 'Aramayo', 'Instalación y Certificación de Redes'),
  ('Diego', 'Aramayo', 'Redes I'),
  ('Diego', 'Aramayo', 'Redes II'),
  ('Diego', 'Aramayo', 'Sistemas Digitales II'),
  ('Diego', 'Aramayo', 'Sistemas de Comunicación Óptica'),
  ('Diego', 'Aramayo', 'Sistemas de Radiocomunicación I'),
  ('Diego', 'Aramayo', 'Sistemas de Radiocomunicación II'),
  ('Diego', 'Aramayo', 'Tecnologías Inalámbricas'),
  ('Edmundo', 'Rivas', 'Hardware, Software y Redes'),
  ('Edmundo', 'Rivas', 'Ingeniería de Software II'),
  ('Edmundo', 'Rivas', 'Modalidad de Grado - Examen de Grado Redes'),
  ('Edmundo', 'Rivas', 'Programación Básica'),
  ('Edmundo', 'Rivas', 'Seguridad en Redes'),
  ('Edmundo', 'Rivas', 'Sistemas Operativos II'),
  ('Edmundo', 'Rivas', 'Taller de Sistemas Operativos I'),
  ('Edmundo', 'Rivas', 'Taller de Sistemas Operativos II'),
  ('Elizabeth', 'Severiche', 'Inglés Técnico I'),
  ('Elizabeth', 'Severiche', 'Inglés Técnico II'),
  ('Emily', 'Arteaga', 'Medicina (laboratorio)'),
  ('Ernesto', 'Soto', 'Desarrollo de Sistemas I'),
  ('Ernesto', 'Soto', 'Ingeniería de Software I'),
  ('Ernesto', 'Soto', 'Modalidad de Grado - Examen de Grado Sistemas'),
  ('Ernesto', 'Soto', 'Sistemas de Información II'),
  ('Esther', 'Veizaga', 'Estructuras Discretas'),
  ('Esther', 'Veizaga', 'Hardware, Software y Redes'),
  ('Esther', 'Veizaga', 'Informática Educativa'),
  ('Esther', 'Veizaga', 'Programación Básica'),
  ('Freddy', 'Tinajeros', 'Medicina (laboratorio)'),
  ('Gineth', 'Salo', 'Medicina (laboratorio)'),
  ('Gustavo', 'Pérez', 'Hardware, Software y Redes'),
  ('Gustavo', 'Pérez', 'Informática Educativa'),
  ('Gustavo', 'Pérez', 'Taller de Redes'),
  ('Gustavo', 'Pérez', 'Tecnologías Inalámbricas'),
  ('Gustavo', 'Tantani', 'Base de Datos II'),
  ('Gustavo', 'Tantani', 'Circuitos Eléctricos II'),
  ('Gustavo', 'Tantani', 'Desarrollo de Sistemas I'),
  ('Gustavo', 'Tantani', 'Estructura de Datos'),
  ('Gustavo', 'Tantani', 'Estructuras Discretas'),
  ('Gustavo', 'Tantani', 'Programación Básica'),
  ('Gustavo', 'Tantani', 'Programación I'),
  ('Gustavo', 'Tantani', 'Programación IV'),
  ('Gustavo', 'Tantani', 'Sistemas Digitales I'),
  ('Gustavo', 'Tantani', 'Sistemas Digitales II'),
  ('Gustavo', 'Tantani', 'Sistemas Operativos I'),
  ('Gustavo', 'Tantani', 'Sistemas de Información III'),
  ('Hernán', 'Rodríguez', 'Aplicaciones Móviles'),
  ('Hernán', 'Rodríguez', 'Programación Básica'),
  ('Hernán', 'Rodríguez', 'Sistemas de Información II'),
  ('Hernán', 'Rodríguez', 'Sistemas de Información III'),
  ('Hernán', 'Rodríguez', 'Tecnología Web II'),
  ('Hugo', 'Guzmán', 'Base de Datos I'),
  ('Hugo', 'Guzmán', 'Base de Datos II'),
  ('Hugo', 'Guzmán', 'Desarrollo de Sistemas II'),
  ('Hugo', 'Guzmán', 'Hardware, Software y Redes'),
  ('Hugo', 'Guzmán', 'Medicina (laboratorio)'),
  ('Hugo', 'Guzmán', 'Programación Básica'),
  ('Hugo', 'Guzmán', 'Seguridad Informática'),
  ('Hugo', 'Guzmán', 'Sistemas Operativos I'),
  ('Hugo', 'Guzmán', 'Sistemas de Información I'),
  ('Hugo', 'Guzmán', 'Tecnología de Base de Datos I'),
  ('Iván', 'Paz', 'Fundamentos de Sistemas de Comunicación'),
  ('Iván', 'Paz', 'Informática Educativa'),
  ('Iván', 'Paz', 'Redes I'),
  ('Iván', 'Paz', 'Redes IV'),
  ('Iván', 'Paz', 'Seguridad Informática'),
  ('Iván', 'Paz', 'Seguridad en Redes'),
  ('Jaime', 'Zambrana', 'Aplicaciones Móviles'),
  ('Jaime', 'Zambrana', 'Base de Datos I'),
  ('Jaime', 'Zambrana', 'Diseño Web I'),
  ('Jaime', 'Zambrana', 'Inteligencia Artificial'),
  ('Jaime', 'Zambrana', 'Programación Básica'),
  ('Jaime', 'Zambrana', 'Programación III'),
  ('Jaime', 'Zambrana', 'Sistemas Multimedia'),
  ('Jaime', 'Zambrana', 'Tecnología Web II'),
  ('Jared', 'López', 'Administración de Base de Datos I'),
  ('Jared', 'López', 'Base de Datos I'),
  ('Jared', 'López', 'Informática Educativa'),
  ('Jared', 'López', 'Programación I'),
  ('Jared', 'López', 'Programación II'),
  ('Jared', 'López', 'Programación IV'),
  ('Jared', 'López', 'Tecnología Web I'),
  ('Jared', 'López', 'Tecnología Web II'),
  ('Jared', 'López', 'Tecnología de Base de Datos I'),
  ('Javier', 'Bonifaz', 'Programación Básica'),
  ('Javier', 'Bonifaz', 'Sistemas de Radiocomunicación I'),
  ('Javier', 'López', 'Base de Datos I'),
  ('Javier', 'López', 'Estadística Descriptiva'),
  ('Javier', 'López', 'Estadística Inferencial'),
  ('Javier', 'López', 'Hardware, Software y Redes'),
  ('Javier', 'López', 'Programación Básica'),
  ('Javier', 'López', 'Programación Numérica'),
  ('Javier', 'López', 'Programación de Aplicaciones'),
  ('Jeanine', 'Yépez', 'Deontología'),
  ('Jesús', 'Torrez', 'Estadística Inferencial'),
  ('Jimmy', 'Requena', 'Auditoría de Sistemas'),
  ('Jimmy', 'Requena', 'Base de Datos II'),
  ('Jimmy', 'Requena', 'Diseño Web I'),
  ('Jimmy', 'Requena', 'Ingeniería de Software I'),
  ('Jimmy', 'Requena', 'Inteligencia Artificial'),
  ('Jimmy', 'Requena', 'Inteligencia de Negocios'),
  ('Jimmy', 'Requena', 'Programación IV'),
  ('Jimmy', 'Requena', 'Programación Web II'),
  ('Jimmy', 'Requena', 'Sistemas de Información I'),
  ('Jimmy', 'Requena', 'Sistemas de Información II'),
  ('Jimmy', 'Requena', 'Taller de Redes'),
  ('Jimmy', 'Requena', 'Tecnología Web II'),
  ('José', 'Castro', 'Programación I'),
  ('José', 'Cuéllar', 'Investigación de Mercado I'),
  ('Lili', 'Jiménez', 'Diseño Web I'),
  ('Lili', 'Jiménez', 'Estructuras Discretas'),
  ('Lili', 'Jiménez', 'Programación Básica'),
  ('Lili', 'Jiménez', 'Programación I'),
  ('Lili', 'Jiménez', 'Sistemas Operativos I'),
  ('Lili', 'Veizaga', 'Hardware, Software y Redes'),
  ('Luis', 'Orozco', 'Electrónica II'),
  ('Luis', 'Orozco', 'Hardware, Software y Redes'),
  ('Luis', 'Orozco', 'Redes I'),
  ('Luis', 'Orozco', 'Redes II'),
  ('Luis', 'Orozco', 'Redes III'),
  ('Luis', 'Orozco', 'Seguridad Informática'),
  ('Luis', 'Orozco', 'Sistemas Operativos II'),
  ('Luis', 'Orozco', 'Taller de Sistemas Operativos II'),
  ('Marco Antonio', 'Vidal', 'Hardware, Software y Redes'),
  ('Marco Antonio', 'Vidal', 'Informática Educativa'),
  ('Marco Antonio', 'Vidal', 'Ingeniería de Software I'),
  ('Marco Antonio', 'Vidal', 'Ingeniería de Software II'),
  ('Marco Antonio', 'Vidal', 'Programación Básica'),
  ('Marco Antonio', 'Vidal', 'Programación I'),
  ('Marco Antonio', 'Vidal', 'Programación II'),
  ('María', 'Colque', 'Análisis de Sistemas y Señales'),
  ('María', 'Colque', 'Electrónica II'),
  ('María', 'Colque', 'Hardware, Software y Redes'),
  ('María', 'Colque', 'Medios de Transmisión'),
  ('María', 'Colque', 'Modalidad de Grado - Examen de Grado Redes'),
  ('María', 'Colque', 'Programación Básica'),
  ('María', 'Colque', 'Redes I'),
  ('María', 'Colque', 'Redes II'),
  ('María', 'Colque', 'Sistemas Digitales II'),
  ('María', 'Colque', 'Sistemas de Radiocomunicación II'),
  ('Mauren', 'Salvatierra', 'Medicina (laboratorio)'),
  ('Miguel', 'Macías', 'Informática Educativa'),
  ('Miguel', 'Macías', 'Programación Básica'),
  ('Miguel', 'Macías', 'Programación II'),
  ('Miguel', 'Macías', 'Programación III'),
  ('Miguel', 'Macías', 'Programación IV'),
  ('Naín', 'Rivas', 'Estructuras Discretas'),
  ('Naín', 'Rivas', 'Inglés Técnico I'),
  ('Naín', 'Rivas', 'Inglés Técnico II'),
  ('Pablo', 'Moscoso', 'Estructura de Datos'),
  ('Pablo', 'Moscoso', 'Tecnología de Base de Datos I'),
  ('Paul', 'Melgar', 'Administración de Base de Datos I'),
  ('Paul', 'Melgar', 'Base de Datos II'),
  ('Paul', 'Melgar', 'Desarrollo de Sistemas II'),
  ('Paul', 'Melgar', 'Diseño Web II'),
  ('Paul', 'Melgar', 'Programación I'),
  ('Paul', 'Melgar', 'Programación Web II'),
  ('Paul', 'Melgar', 'Sistemas Digitales II'),
  ('Ruth', 'Gascher', 'Inglés Técnico I'),
  ('Ruth', 'Gascher', 'Inglés Técnico II'),
  ('Sergio', 'Cruz Sequeiros', 'Derecho Administrativo y Regulatorio'),
  ('Sergio', 'Cruz Sequeiros', 'Derecho de Hidrocarburos'),
  ('Teresa', 'Gutiérrez', 'Herramientas Digitales'),
  ('Teresa', 'Justiniano', 'Herramientas Digitales'),
  ('Wilber', 'Baspineiro', 'Investigación de Mercado I'),
  ('Wilder', 'Mendoza', 'Trading'),
  ('Wilmer', 'Campos', 'Medicina (laboratorio)'),
  ('Wilson', 'Cruz', 'Desarrollo de Sistemas I'),
  ('Wilson', 'Cruz', 'Diseño Web II'),
  ('Wilson', 'Cruz', 'Inteligencia Artificial'),
  ('Wilson', 'Cruz', 'Modalidad de Grado - Examen de Grado Sistemas'),
  ('Wilson', 'Cruz', 'Programación I'),
  ('Wilson', 'Cruz', 'Programación II'),
  ('Wilson', 'Cruz', 'Programación Web I'),
  ('Wilson', 'Cruz', 'Programación Web II'),
  ('Wilson', 'Cruz', 'Sistemas Operativos I'),
  ('Wilson', 'Cruz', 'Sistemas de Información I'),
  ('Wilson', 'Cruz', 'Taller de Sistemas Operativos I'),
  ('Wilson', 'Cruz', 'Tecnología Web I'),
  ('Wilson', 'Cruz', 'Tecnología de Base de Datos I'),
  ('Yolanda', 'Morón', 'Auditoría de Sistemas'),
  ('Ysnaider', 'Castro', 'Investigación Operativa I'),
  ('Álvaro', 'Moscoso', 'Administración de Base de Datos I'),
  ('Álvaro', 'Moscoso', 'Desarrollo de Sistemas II'),
  ('Álvaro', 'Moscoso', 'Estructura de Datos'),
  ('Álvaro', 'Moscoso', 'Ingeniería de Software I'),
  ('Álvaro', 'Moscoso', 'Ingeniería de Software II'),
  ('Álvaro', 'Moscoso', 'Programación Web I'),
  ('Álvaro', 'Moscoso', 'Sistemas de Información II'),
  ('Álvaro', 'Moscoso', 'Tecnología Web I')
) v(nombres, apellidos, materia)
join public.docentes dc on dc.nombres = v.nombres and dc.apellidos = v.apellidos
join public.materias m on m.nombre = v.materia;

commit;
